# Generated by Django 3.1.1 on 2020-09-10 19:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('items', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.PositiveSmallIntegerField(help_text='Сумма сделки:')),
                ('quantity', models.PositiveSmallIntegerField(default=1, help_text='Количество товара (шт):')),
                ('date', models.DateTimeField(blank=True, default=django.utils.timezone.now, help_text='Дата и время регистрации сделки:', null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.item')),
            ],
            options={
                'ordering': ['customer'],
            },
        ),
    ]
