# Generated by Django 3.1.1 on 2020-09-10 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название камня:', max_length=100)),
                ('cost', models.IntegerField(default=500, help_text='Цена:')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
